// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pbhello.proto

package pbhello

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	client "roc/client"
	parcel "roc/parcel"
	context "roc/parcel/context"
	server "roc/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// request params.
type SayReq struct {
	Inc uint32 `protobuf:"varint,1,opt,name=inc,proto3" json:"inc,omitempty"`
}

func (m *SayReq) Reset()         { *m = SayReq{} }
func (m *SayReq) String() string { return proto.CompactTextString(m) }
func (*SayReq) ProtoMessage()    {}
func (*SayReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc7e4ba46bfc0c1, []int{0}
}
func (m *SayReq) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SayReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SayReq.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SayReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayReq.Merge(m, src)
}
func (m *SayReq) XXX_Size() int {
	return m.Size()
}
func (m *SayReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SayReq.DiscardUnknown(m)
}

var xxx_messageInfo_SayReq proto.InternalMessageInfo

func (m *SayReq) GetInc() uint32 {
	if m != nil {
		return m.Inc
	}
	return 0
}

// response content.
type SayRsp struct {
	Inc uint32 `protobuf:"varint,1,opt,name=inc,proto3" json:"inc,omitempty"`
}

func (m *SayRsp) Reset()         { *m = SayRsp{} }
func (m *SayRsp) String() string { return proto.CompactTextString(m) }
func (*SayRsp) ProtoMessage()    {}
func (*SayRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc7e4ba46bfc0c1, []int{1}
}
func (m *SayRsp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SayRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SayRsp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SayRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SayRsp.Merge(m, src)
}
func (m *SayRsp) XXX_Size() int {
	return m.Size()
}
func (m *SayRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_SayRsp.DiscardUnknown(m)
}

var xxx_messageInfo_SayRsp proto.InternalMessageInfo

func (m *SayRsp) GetInc() uint32 {
	if m != nil {
		return m.Inc
	}
	return 0
}

func init() {
	proto.RegisterType((*SayReq)(nil), "SayReq")
	proto.RegisterType((*SayRsp)(nil), "SayRsp")
}

func init() { proto.RegisterFile("pbhello.proto", fileDescriptor_2bc7e4ba46bfc0c1) }

var fileDescriptor_2bc7e4ba46bfc0c1 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x48, 0xca, 0x48,
	0xcd, 0xc9, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe2, 0x62, 0x0b, 0x4e, 0xac,
	0x0c, 0x4a, 0x2d, 0x14, 0x12, 0xe0, 0x62, 0xce, 0xcc, 0x4b, 0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0,
	0x0d, 0x02, 0x31, 0x61, 0x72, 0xc5, 0x05, 0x98, 0x72, 0x46, 0x05, 0x5c, 0x5c, 0x1e, 0x20, 0x63,
	0xc2, 0xf3, 0x8b, 0x72, 0x52, 0x84, 0x24, 0xb9, 0x98, 0x83, 0x13, 0x2b, 0x85, 0xd8, 0xf5, 0x20,
	0x66, 0x49, 0x41, 0x18, 0xc5, 0x05, 0x4a, 0x0c, 0x42, 0x8a, 0x5c, 0x9c, 0xc1, 0x89, 0x95, 0xc1,
	0x25, 0x45, 0xa9, 0x89, 0xb9, 0xd8, 0x14, 0x68, 0x30, 0x0a, 0xa9, 0x70, 0x71, 0x05, 0x27, 0x56,
	0x3a, 0x67, 0x24, 0xe6, 0xe5, 0xa5, 0xe6, 0x60, 0x57, 0x63, 0xc0, 0xe8, 0x24, 0x71, 0xe2, 0x91,
	0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1,
	0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x49, 0x6c, 0x60, 0xaf, 0x18, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x29, 0xf5, 0x82, 0x28, 0xdb, 0x00, 0x00, 0x00,
}

func (m *SayReq) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SayReq) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SayReq) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Inc != 0 {
		i = encodeVarintPbhello(dAtA, i, uint64(m.Inc))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SayRsp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SayRsp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SayRsp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Inc != 0 {
		i = encodeVarintPbhello(dAtA, i, uint64(m.Inc))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPbhello(dAtA []byte, offset int, v uint64) int {
	offset -= sovPbhello(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.RocClient
var _ server.RocServer
var _ parcel.RocPacket

// This is a compile-time assertion to ensure that this generated file
// is compatible with the roc package it is being compiled against.
const _ = server.SupportPackageIsVersion1

type HelloWorldClient interface {
	// requestResponse or fireAndForget.
	Say(c *context.Context, req *SayReq, opts ...client.InvokeOptions) (*SayRsp, error)
	// requestStream.
	// SayReq is channel params.
	SayStream(c *context.Context, req *SayReq, opts ...client.InvokeOptions) (chan *SayRsp, chan error)
	// requestChannel.
	// SayReq and SayRsp is channel.
	SayChannel(c *context.Context, req chan *SayReq, errIn chan error, opts ...client.InvokeOptions) (chan *SayRsp, chan error)
}

type helloWorldClient struct {
	c *client.RocClient
}

func NewHelloWorldClient(c *client.RocClient) HelloWorldClient {
	return &helloWorldClient{c}
}

func (cc *helloWorldClient) Say(c *context.Context, req *SayReq, opts ...client.InvokeOptions) (*SayRsp, error) {
	rsp := &SayRsp{}
	err := cc.c.InvokeRR(c, "HelloWorld.Say", req, rsp, opts...)
	return rsp, err
}

func (cc *helloWorldClient) SayStream(c *context.Context, req *SayReq, opts ...client.InvokeOptions) (chan *SayRsp, chan error) {
	data, errs := cc.c.InvokeRS(c, "HelloWorld.SayStream", req, opts...)
	var rsp = make(chan *SayRsp)
	go func() {
		for b := range data {
			v := &SayRsp{}
			err := cc.c.Codec().Decode(b, v)
			if err != nil {
				errs <- err
				break
			}
			rsp <- v
		}
		close(rsp)
	}()
	return rsp, errs
}

func (cc *helloWorldClient) SayChannel(c *context.Context, req chan *SayReq, errIn chan error, opts ...client.InvokeOptions) (chan *SayRsp, chan error) {
	var in = make(chan []byte)
	go func() {
		for b := range req {
			v, err := cc.c.Codec().Encode(b)
			if err != nil {
				errIn <- err
				break
			}
			in <- v
		}
		close(in)
	}()

	data, errs := cc.c.InvokeRC(c, "HelloWorld.SayChannel", in, errIn, opts...)
	var rsp = make(chan *SayRsp)
	go func() {
		for b := range data {
			v := &SayRsp{}
			err := cc.c.Codec().Decode(b, v)
			if err != nil {
				errs <- err
				break
			}
			rsp <- v
		}
		close(rsp)
	}()
	return rsp, errs
}

// HelloWorldServer is the server API for HelloWorld service.
type HelloWorldServer interface {
	// requestResponse or fireAndForget.
	Say(c *context.Context, req *SayReq) (rsp *SayRsp, err error)
	// requestStream.
	// SayReq is channel params.
	SayStream(c *context.Context, req *SayReq) (chan *SayRsp, chan error)
	// requestChannel.
	// SayReq and SayRsp is channel.
	SayChannel(c *context.Context, req chan *SayReq, errIn chan error) (chan *SayRsp, chan error)
}

func RegisterHelloWorldServer(s *server.RocServer, h HelloWorldServer) {
	var r = &helloWorldHandler{h: h, s: s}
	s.RegisterHandler("HelloWorld.Say", r.Say)
	s.RegisterStreamHandler("HelloWorld.SayStream", r.SayStream)
	s.RegisterChannelHandler("HelloWorld.SayChannel", r.SayChannel)
}

type helloWorldHandler struct {
	h HelloWorldServer
	s *server.RocServer
}

func (r *helloWorldHandler) Say(c *context.Context, req *parcel.RocPacket, interrupt parcel.Interceptor) (rsp proto.Message, err error) {
	var in SayReq
	err = r.s.Codec().Decode(req.Bytes(), &in)
	if err != nil {
		return nil, err
	}
	if interrupt == nil {
		return r.h.Say(c, &in)
	}
	f := func(c *context.Context, req proto.Message) (proto.Message, error) {
		return r.h.Say(c, req.(*SayReq))
	}
	return interrupt(c, &in, f)
}

func (r *helloWorldHandler) SayStream(c *context.Context, req *parcel.RocPacket) (chan proto.Message, chan error) {
	var errs = make(chan error)
	var in SayReq
	err := r.s.Codec().Decode(req.Bytes(), &in)
	if err != nil {
		errs <- err
		close(errs)
		return nil, errs
	}

	out, outErrs := r.h.SayStream(c, &in)
	var rsp = make(chan proto.Message, len(out))

	go func() {
	QUIT:
		for {
			select {
			case d, ok := <-out:
				if ok {
					rsp <- d
				} else {
					break QUIT
				}
			case err := <-outErrs:
				errs <- err
				break QUIT
			}
		}
		close(rsp)
		close(errs)
	}()
	return rsp, errs
}

func (r *helloWorldHandler) SayChannel(c *context.Context, req chan *parcel.RocPacket, errIn chan error) (chan proto.Message, chan error) {
	var in = make(chan *SayReq)
	go func() {
		for b := range req {
			var v = &SayReq{}
			err := r.s.Codec().Decode(b.Bytes(), v)
			if err != nil {
				errIn <- err
				break
			}
			in <- v
		}
		close(in)
	}()

	out, outErrs := r.h.SayChannel(c, in, errIn)
	var rsp = make(chan proto.Message)

	go func() {
		for d := range out {
			rsp <- d
		}
		close(rsp)
	}()
	return rsp, outErrs
}

func (m *SayReq) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Inc != 0 {
		n += 1 + sovPbhello(uint64(m.Inc))
	}
	return n
}

func (m *SayRsp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Inc != 0 {
		n += 1 + sovPbhello(uint64(m.Inc))
	}
	return n
}

func sovPbhello(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPbhello(x uint64) (n int) {
	return sovPbhello(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SayReq) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPbhello
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SayReq: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SayReq: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inc", wireType)
			}
			m.Inc = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPbhello
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Inc |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPbhello(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPbhello
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SayRsp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPbhello
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SayRsp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SayRsp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Inc", wireType)
			}
			m.Inc = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPbhello
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Inc |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPbhello(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPbhello
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPbhello(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPbhello
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPbhello
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPbhello
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPbhello
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPbhello
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPbhello
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPbhello        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPbhello          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPbhello = fmt.Errorf("proto: unexpected end of group")
)
